// Refreshes src/generated/tools.snapshot.json from a running Central City server.
//
//   CC_SDK_ORIGIN=http://127.0.0.1:4310 npx tsx scripts/snapshot-tools.ts
//
// It lists /mcp/open, creates one throwaway AI workspace there to get a key, and lists /mcp.
// Point it at a LOCAL development server: it creates a workspace.
import { writeFileSync } from 'node:fs';
import { HttpMcpTransport, bearer } from '../src/index.js';

const origin = process.env.CC_SDK_ORIGIN ?? 'http://127.0.0.1:4310';
type Tool = {
  name: string;
  title?: string;
  inputSchema?: { properties?: Record<string, unknown>; required?: string[] };
  outputSchema?: unknown;
  annotations?: Record<string, unknown>;
};

async function list(endpoint: string, token?: string): Promise<Tool[]> {
  const transport = new HttpMcpTransport({
    endpoint,
    ...(token ? { auth: bearer(token) } : {}),
    clientInfo: { name: '@centralcity/sdk snapshot', version: '0.0.0' },
  });
  return (await transport.request<{ tools: Tool[] }>('tools/list')).tools;
}

const open = await list(`${origin}/mcp/open`);
const created = await new HttpMcpTransport({ endpoint: `${origin}/mcp/open` }).callTool<{
  workspace_key: string;
}>('city_create_workspace', { name: 'SDK snapshot', idempotency_key: crypto.randomUUID() });
const authenticated = await list(`${origin}/mcp`, created.workspace_key);

const shape = (tool: Tool) => ({
  name: tool.name,
  title: tool.title ?? null,
  input: {
    properties: Object.keys(tool.inputSchema?.properties ?? {}).sort(),
    required: [...(tool.inputSchema?.required ?? [])].sort(),
  },
  annotations: {
    readOnlyHint: tool.annotations?.readOnlyHint === true,
    idempotentHint: tool.annotations?.idempotentHint !== false,
    destructiveHint: tool.annotations?.destructiveHint === true,
  },
});
const snapshot = {
  _comment: 'Generated by scripts/snapshot-tools.ts from a running server. Do not edit by hand.',
  generated_at: new Date().toISOString().slice(0, 10),
  open: open.map(shape).sort((a, b) => a.name.localeCompare(b.name)),
  authenticated: authenticated.map(shape).sort((a, b) => a.name.localeCompare(b.name)),
};
writeFileSync(
  new URL('../src/generated/tools.snapshot.json', import.meta.url),
  `${JSON.stringify(snapshot, null, 2)}\n`,
);
writeFileSync(new URL('../src/generated/tools.ts', import.meta.url), renderTable(snapshot));
console.log(`open: ${snapshot.open.length} tools, authenticated: ${snapshot.authenticated.length} tools`);

/**
 * A TypeScript module (no JSON import attributes, so Node 20.3 works). The two endpoints are kept
 * apart: some tools exist on both with different inputs (the open room tools take room_credential).
 */
function renderTable(data: typeof snapshot): string {
  const table = (tools: ReturnType<typeof shape>[]) =>
    Object.fromEntries(
      tools.map((tool) => [
        tool.name,
        {
          properties: tool.input.properties,
          required: tool.input.required,
          readOnly: tool.annotations.readOnlyHint,
          idempotent: tool.annotations.idempotentHint,
        },
      ]),
    );
  return `// Generated by scripts/snapshot-tools.ts (${data.generated_at}). Do not edit by hand.
import type { ToolTable } from '../table.js';

export const TOOLS: ToolTable = ${JSON.stringify({ open: table(data.open), mcp: table(data.authenticated) }, null, 2)};
`;
}
